blog/urls.py
from django.urls import path
from .views import render_posts, post_detail

#poder diferenciar y utilizar todas las urls
app_name = "blog"

urlpatterns = [
    path("", render_posts, name="posts"),
    path("<int:post_id>", post_detail, name="post_detail"),
]

django_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from portfolio import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('blog/', include('blog.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
import datetime


class Post(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to="blog/images")
    date = models.DateField(datetime.date.today)

portfolio/models.py
from django.db import models
from django.db.models.fields import CharField, URLField
from django.db.models.fields.files import ImageField


class Project(models.Model):
    title = CharField(max_length=100)
    description = CharField(max_length=250)
    image = ImageField(upload_to="portfolio/images/")
    url = URLField(blank=True)

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post

def render_posts(request):
    posts = Post.objects.all()
    return render(request, 'posts.html', {'posts': posts})

def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id) 
    return render(request, 'post_detail.html', {"post": post})

portfolio/views.py
from django.shortcuts import render
from .models import Project


def home(request):
    projects = Project.objects.all()


    return render(request, 'home.html' , {'projects': projects})

blog/templates/post_detail.html
{% extends 'layout.html' %}

{% block content %}

<div class="text-center">
    <h2>{{post.title}}</h2>
    <h3 class="my-2 h5 text-muted">{{post.date | date:'F jS Y'}}</h3>

    <img src="{{post.image.url}}" alt="{{post.description}}" class="img-fluid">

    <div class="my-4">
        <p>{{post.description | safe}}</p>
    </div>
</div>

{% endblock %}

blog/templates/posts.html
{% extends 'layout.html'%}

{% block content %}

<h1>posts</h1>

{% for post in posts%}

<div class="p-3">
    <div class="card card-body bg-black">
        <div class="row">
            <div class="col-3">
                <img src="{{post.image.url}}" alt="{{post.title}}" class="img-fluid">
            </div>

            <div class="col-9">
                <h2>{{post.title}}</h2>
                <p>{{post.description | striptags | truncatechars:100 }}</p>
                <p>{{post.date | date:'M d Y'|upper}}</p>


                <a href="{% url 'blog:post_detail' post.id %}" class="btn btn-primary">{{post.title}}</a>
            </div>
        </div>
    </div>
</div>

{% endfor %}

{% endblock%}

portfolio/templates/home.html
{% extends 'layout.html'%}

{% block content %}

{% load static %}

<header class="row bg-black">
    <div class="col-md-4">
        <img src="{% static 'portfolio/download.jpeg' %}" alt="">
    </div>

    <div class="col-md-8 my-auto">
        <h1>soy diego</h1>
        <h3>soy un full stack python developer</h3>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quas, doloremque consequuntur aspernatur, excepturi
            impedit provident corporis quod dolorem eligendi consectetur, veniam soluta. Nesciunt accusantium eius,
            repellat laboriosam est atque, perferendis impedit vitae doloremque rerum consectetur iste necessitatibus
            molestiae. Tempore eveniet dolorum sapiente consequatur quia odit eligendi! Aut, velit? Itaque vel ullam
            fugiat, officiis quidem aut? Enim modi dolores doloremque natus obcaecati eaque ea eius maiores, labore
            tempore autem, officiis, repellendus nisi hic ratione aliquid harum? Similique beatae in repellat quasi
            neque cupiditate iusto porro minus sit expedita, magni delectus, soluta sunt temporibus doloribus,
            voluptates molestias adipisci ratione at cum aperiam.</p>
        <a href="{% static 'portfolio/certificado.pdf' %}" class="btn btn-primary btn-lg rounded-0 my-3">Download cv</a>
    </div>
</header>

<div class="row my-4 text-center">
    <h3>Projects</h3>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat, ad!</p>

    {% for project in projects%}

    <div class="col-md-4 p-4">
        <div class="card bg-black card-project">
            <div class="card-body">
                <h2>{{project.title}}</h2>
                <p>{{project.description}}</p>
                <img src="{{project.image.url}}" alt="{{project.title}}" class="img-fluid">

                {% if project.url%}
                <a href="{{project.url}}" class="btn btn-light rounded-0 btn-sm" target="_blank">{{project.url}}</a>
                {% endif %}
            </div>
        </div>
    </div>

    {% endfor %}

    {% endblock %}

</div>

portfolio/templates/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Django portfolio</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'main.css' %}">
</head>
<body class="text-light">
    
    {% include 'partials/navbar.html'%}

    <div class="container p-4">
    {% block content %}
    {% endblock %}
    </div>
    
    <footer>Footer</footer>

</body>
</html>

portfolio/templates/partials/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark"> <!-- bg y navbar me sirven para cambiarle el color a la barra de navegacion -->
    <div class="container"> <!-- container me sirve para poder cambiar los inconos dentro del navbar (puedo colocarle container-fluid para q vaya hacia un lado)-->
      <a class="navbar-brand" href="/">Grafotec</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ms-auto"> <!-- aca al ul le estoy agregando un margin -->
          <li class="nav-item">
            <a class="nav-link" href="{% url 'blog:posts' %}">Blog</a>
          </li>
          <li class="nav-item d-flex align-items-center">
            <a class="btn btn-primary btn-sm" href="{% static 'portfolio/certificado.pdf'%}" target="_blank">Download CV</a> <!--la etiqueta target sirve para abrir enlaces en una siguiente pestaña-->
          </li>
        </ul>
      </div>
    </div>
  </nav>